# Generated by Django 5.2.4 on 2025-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('bank', '銀行帳戶'), ('securities', '證券帳戶')], max_length=10)),
            ],
        ),
    ]
